# Generated by Django 2.2.4 on 2019-11-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191111_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='preview_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
