# Generated by Django 2.2.4 on 2019-11-10 22:11

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191111_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='preview_image',
            field=models.ImageField(upload_to=home.models.image_path),
        ),
    ]
