# Generated by Django 2.2.4 on 2019-11-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191111_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='preview_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
