# Generated by Django 2.2.4 on 2019-11-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191111_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='word_file',
            field=models.FileField(default=-1, upload_to='files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announce',
            name='presentation',
            field=models.FileField(default=-1, upload_to='files'),
            preserve_default=False,
        ),
    ]
