# Generated by Django 2.2.4 on 2019-11-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191111_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='announce',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='announce',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
